# Generated by Django 5.0.2 on 2024-02-16 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20)),
                ('orgid', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
                ('address', models.TextField(max_length=300)),
                ('is_deleted', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolRec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recid', models.CharField(max_length=50)),
                ('user', models.CharField(max_length=100)),
                ('school', models.CharField(max_length=100)),
                ('entry_date', models.DateField()),
                ('exit_date', models.DateField()),
                ('entry_class', models.CharField(max_length=20)),
                ('passout_class', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achieve_id', models.CharField(max_length=50)),
                ('achieve_date', models.DateField()),
                ('achieve_desc', models.CharField(max_length=100)),
                ('cetrificate', models.FileField(upload_to='')),
                ('is_deleted', models.BooleanField()),
                ('alumni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.schoolrec')),
            ],
        ),
    ]
